### ISSUE TITLE
page/lib material-ui.com doesn't work

### ISSUE THREAD

**Issue by ahinrichs** [QupZilla/qupzilla#2265]
I'm sorry, but this is way too much for me to debug: pages using js lib material-ui are not displayed correctly.

Eg. http://www.material-ui.com/#/components/app-bar

**Comment by nowrep** [comment]
What is your QupZilla version?

**Comment by ahinrichs** [comment]
Uh sorry :-)

QupZilla 2.1.2, QtWebEngine 5.8.0 (ArchLinux)

**Comment by ahinrichs** [comment]
Also tried qupzilla 1.8.2 (ubuntu xenial) and current AppImage, all with the same result. Konqueror 5.0.97 with QTWebEngine 5.8.0 works.

Maybe at least someone else could check it out. Just to know whether it is an issue or a local problem here.

**Comment by Martii** [comment]
@ahinrichs 
> Maybe at least someone else could check it out. Just to know whether it is an issue or a local problem here.

Re:
> Eg. http://www.material-ui.com/#/components/app-bar

Since I'm not familiar with the site I don't know what it's supposed to look like... but in SM and OS X QupZilla current HEAD... they appear on the surface to look the same.

Do you have a screen shot *(or video)* of what it is supposed to be doing so I can compare? :question:

**Comment by ahinrichs** [comment]
Thanks for taking a look!

Firefox: ![Firefox](https://intranet.bitscape.de/public/jai4xuuRoghe/ff.png)
QupZilla: ![QupZilla](https://intranet.bitscape.de/public/jai4xuuRoghe/qupzilla.png)

**Comment by Martii** [comment]
@ahinrichs
Using the HEAD of 686ad7eee28d160448f90a218d37a155bf27a005 this is what I see:

<img src="https://cloud.githubusercontent.com/assets/114709/24176222/4ef63ad8-0e60-11e7-9375-4fcd00e25b4e.png" alt="686ad7e views" title="Click to enlarge" width="168" height="105" />

* Top window is my Linux distro of ROSA freshly compiled *(Cursored on that link and does expand when clicked)*
* Lower window is my VNC OS X *(does expand clicked)*

Hope that helps.

**Comment by srazi** [comment]
Same issue here (Windows 10). ~~It is like a css file is not loaded since~~ it works locally. I saved page using FireFox (Webpage, complete) and then I opened it using QupZilla and QupZilla rendered it correctly.

**Update 1:** when I deleted resource folder related to saved html page again it was loaded correctly.
**Update 2:** Using private browsing [the URL](http://www.material-ui.com/#/components/app-bar) was loaded correctly.

**Comment by ahinrichs** [comment]
I can confirm srazi under Linux. The page looks correctly if opened from a firefox saved page (with or without resources) or direct in a private window.

**Comment by Martii** [comment]
* Chromium in my distro of `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36` renders correctly both in incognito and standard.
* SM in private browsing still misaligned... testing local momentarily...

**Comment by Martii** [comment]
Hmmm QtWebEngine seems a bit behind in QupZilla:
* `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.1.99 Chrome/53.0.2785.148 Safari/537.36`

**Comment by Martii** [comment]
I would guess that since SM failed all around, including the resources folder being absent, that the issue lies in the HTML somewhere... might help narrow down what's happening.

**Comment by Martii** [comment]
Those greater than less than are a svg tag:


``` js
<svg style="-moz-user-select: none; display: inline-block; color: rgba(0, 0, 0, 0.87); fill: currentcolor; height: 24px; width: 24px; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;" viewBox="0 0 24 24"><path d="M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z"></path></svg>
```

...

**Comment by Martii** [comment]
Done testing... see results above.

**Comment by ahinrichs** [comment]
As I said: way too much for me... Many thanks from my side.

I tried to setup a simpler show case in order to cross open an issue on the material-ui project. Right now I have a development build with webpack but cannot get the generated source map active in qupzilla. The webinspector always just shows the all-in-one generated webpack - not minified but still not that easy to debug - js. It shows "source map detected" but not really using it... firefox does.

But I cannot finish it yet, will continue later. 

This is current state: [build.zip](https://github.com/QupZilla/qupzilla/files/861898/build.zip)

**Comment by ahinrichs** [comment]
I checked once in a while. It looks like the coming material-ui release will fix it. At least the demo for the upcoming release looks right in qupzilla.
